controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_pitch_joint
      - elbow_flex_joint
      - wrist_roll_joint
  - name: fake_gripper_controller
    joints:
      - left_finger_joint
      - right_finger_joint